#!/usr/bin/env bash
set -e

rails=3.2.11 orm=active_record bundle install --quiet
rails=3.2.11 orm=active_record bundle exec rake

rails=3.2.11 orm=mongoid bundle install --quiet
rails=3.2.11 orm=mongoid bundle exec rake

rails=3.2.11 orm=mongo_mapper bundle install --quiet
rails=3.2.11 orm=mongo_mapper bundle exec rake
